export const MAPPING: Record<string, string[]> = {
	ProcessResources: [
		'Process',
		'Line',
		'Substation',
		'VoltageLevel',
		'Bay',
		'ConductingEquipment',
		'GeneralEquipment',
		'ConnectivityNode',
		'Function',
		'SubFunction',
		'EqFunction',
		'EqSubFunction',
	],
	PowerSystemRelations: ['Function', 'SubFunction', 'EqFunction', 'EqSubFunction'],
	LNodeInputs: ['LNode'],
	LNodeOutputs: ['LNode'],
	LNodeSpecNaming: ['LNode'],
	DOS: ['LNode'],
	FunctionSclRef: ['Function', 'SubFunction', 'EqFunction', 'EqSubFunction'],
	Variable: [
		'Process',
		'Line',
		'Substation',
		'VoltageLevel',
		'Bay',
		'GeneralEquipment',
		'ConductingEquipment',
		'Function',
		'SubFunction',
		'EqFunction',
		'EqSubFunction',
	],
	CommunicationServiceSpecifications: ['SubNetwork'],
	ServiceSpecifications: ['SCL'],
	AllocationRole: ['Process', 'Line', 'Substation', 'VoltageLevel', 'Bay'],
	Application: ['Process', 'Line', 'Substation', 'VoltageLevel', 'Bay'],
	BehaviorDescription: [
		'Process',
		'Line',
		'Substation',
		'VoltageLevel',
		'Bay',
		'Function',
		'SubFunction',
		'EqFunction',
		'EqSubFunction',
		'LNode',
	],
	Project: ['SCL'],
	FunctionTemplate: ['SCL'],
}
