// Definition types for element metadata from XSD
// These types represent the JSON structure generated by the CLI (generate.py)

import type { Namespace } from './records'

// --- XPath constraint types (mirrors cli/xpath_parser.py) ---

export type XPathStepKind = 'self' | 'name' | 'wildcard' | 'ns-wildcard'

export type XPathStep = {
	readonly kind: XPathStepKind
	readonly value?: string
}

export type SelectorPath = {
	readonly deep?: true
	readonly steps: readonly XPathStep[]
}

export type FieldTargetKind = 'element' | 'attribute' | 'wildcard' | 'ns-wildcard'

export type FieldTarget = {
	readonly kind: FieldTargetKind
	readonly value?: string
	readonly isAttribute?: true
}

export type ConstraintField = {
	readonly deep?: true
	readonly steps?: readonly XPathStep[]
	readonly target: FieldTarget
}

export type IdentityConstraint = {
	readonly kind: 'unique' | 'key' | 'keyref'
	readonly name: string
	readonly refer?: string
	readonly deep?: true
	readonly selector: readonly SelectorPath[]
	readonly fields: readonly ConstraintField[]
}

// --- Facets ---

export type Facets = {
	readonly enumeration?: readonly string[]
	readonly pattern?: readonly string[]
	readonly minLength?: number
	readonly maxLength?: number
	readonly length?: number
	readonly minInclusive?: number | string
	readonly maxInclusive?: number | string
	readonly minExclusive?: number | string
	readonly maxExclusive?: number | string
	readonly totalDigits?: number
	readonly fractionDigits?: number
	readonly whiteSpace?: 'preserve' | 'replace' | 'collapse'
}

// --- Attribute / child / text definitions ---

export type AttributeDefinition = {
	readonly required?: true
	readonly default?: string
	readonly fixed?: string
	readonly namespace?: Namespace
	readonly facets?: Facets
}

export type ChildDefinition = {
	readonly required?: true
	readonly minOccurs?: number
	readonly maxOccurs?: number
	readonly constraints?: readonly IdentityConstraint[]
}

export type ChoiceGroup = {
	readonly options: readonly string[]
	readonly minOccurs?: number
	readonly maxOccurs?: number
}

export type TextContent = {
	readonly facets?: Facets
}

// --- Element definition ---

export type ElementDefinition = {
	readonly tag: string
	readonly namespace: Namespace
	readonly documentation?: string
	readonly parents: readonly string[]
	readonly attributes: {
		readonly sequence: readonly string[]
		readonly details: Record<string, AttributeDefinition>
	}
	readonly children: {
		readonly sequence: readonly string[]
		readonly any?: true
		readonly details: Record<string, ChildDefinition>
		readonly choices?: readonly ChoiceGroup[]
	}
	readonly constraints?: readonly IdentityConstraint[]
	readonly textContent?: TextContent
}

/**
 * Complete definition — maps element names to their definitions.
 * Each dialecte should define its own specific type extending this.
 */
export type AnyDefinition = Record<string, ElementDefinition>
