// Definition types for element metadata from XSD
// These types represent the JSON structure generated by the CLI (generate.py)

import type { Namespace } from './records'

// --- XPath constraint types (mirrors cli/xpath_parser.py) ---

export type XPathStepKind = 'self' | 'name' | 'wildcard' | 'ns-wildcard'

export type XPathStep = {
	readonly kind: XPathStepKind
	readonly value?: string
}

export type SelectorPath = {
	readonly deep?: true
	readonly steps: readonly XPathStep[]
}

export type FieldTargetKind = 'element' | 'attribute' | 'wildcard' | 'ns-wildcard'

export type FieldTarget = {
	readonly kind: FieldTargetKind
	readonly value?: string
	readonly isAttribute?: true
}

export type ConstraintField = {
	readonly deep?: true
	readonly steps?: readonly XPathStep[]
	readonly target: FieldTarget
}

export type IdentityConstraint = {
	readonly kind: 'unique' | 'key' | 'keyref'
	readonly name: string
	readonly refer?: string
	readonly deep?: true
	readonly selector: readonly SelectorPath[]
	readonly fields: readonly ConstraintField[]
}

// --- Facets ---

export type Facets = {
	readonly enumeration?: readonly string[]
	readonly pattern?: readonly string[]
	readonly minLength?: number
	readonly maxLength?: number
	readonly length?: number
	readonly minInclusive?: number | string
	readonly maxInclusive?: number | string
	readonly minExclusive?: number | string
	readonly maxExclusive?: number | string
	readonly totalDigits?: number
	readonly fractionDigits?: number
	readonly whiteSpace?: 'preserve' | 'replace' | 'collapse'
}

// --- Attribute / child / text definitions ---

/** What a simple value is: an XSD built-in, a list of one, or a union of several. */
export type DataType =
	| { readonly builtin: string; readonly facets?: Facets }
	| { readonly list: DataType; readonly facets?: Facets }
	| { readonly union: readonly DataType[]; readonly facets?: Facets }

export type AttributeDefinition = {
	readonly required?: true
	readonly default?: string
	readonly fixed?: string
	readonly namespace?: Namespace
	readonly facets?: Facets
	/** Absent for a plain string. */
	readonly type?: DataType
}

export type ChildDefinition = {
	readonly required?: true
	readonly minOccurs?: number
	readonly maxOccurs?: number
	readonly constraints?: readonly IdentityConstraint[]
	/**
	 * Per parent→child edge namespace override, present only when the child's
	 * declaring-schema namespace differs from the child element's canonical
	 * `ElementDefinition.namespace` (the same local name declared in another
	 * namespace under this parent). Consumed by `standardizeRecord`, which stamps
	 * it onto the record; absent ⇒ the element's own namespace applies.
	 */
	readonly namespace?: Namespace
	/*
	 * What the child holds as declared under THIS parent, present only when a schema declares the
	 * tag with different content under different parents - and then all of it, never a mix with the
	 * tag-level union. Read with `resolveDefinition`; absent ⇒ the tag-level definition applies.
	 */
	readonly nillable?: true
	readonly attributes?: ElementDefinition['attributes']
	readonly children?: ElementDefinition['children']
	readonly contentModel?: Particle
	readonly textContent?: TextContent
}

/** One node of a content model as the schema wrote it. */
export type Particle =
	| {
			readonly kind: 'sequence' | 'choice' | 'all'
			readonly minOccurs?: number
			readonly maxOccurs?: number
			readonly particles: readonly Particle[]
	  }
	| {
			readonly kind: 'element'
			readonly name: string
			readonly minOccurs?: number
			readonly maxOccurs?: number
	  }
	| {
			readonly kind: 'any'
			readonly namespace?: readonly string[]
			readonly processContents?: string
			readonly minOccurs?: number
			readonly maxOccurs?: number
	  }

export type TextContent = {
	readonly facets?: Facets
	readonly type?: DataType
	readonly default?: string
	readonly fixed?: string
}

// --- Element definition ---

/**
 * What an element is: the union of its declarations when a schema declares the tag differently
 * under different parents. What it holds under one parent is on that parent's edge
 * (`children.details[tag]`); `resolveDefinition` returns the definition in that context.
 */
export type ElementDefinition = {
	readonly tag: string
	readonly namespace: Namespace
	readonly documentation?: string
	readonly parents: readonly string[]
	readonly nillable?: true
	readonly attributes: {
		readonly sequence: readonly string[]
		readonly any?: true
		readonly anyNamespace?: readonly string[]
		readonly details: Record<string, AttributeDefinition>
		readonly identityFields?: readonly string[]
	}
	readonly children: {
		readonly sequence: readonly string[]
		readonly any?: true
		readonly details: Record<string, ChildDefinition>
	}
	readonly contentModel?: Particle
	readonly constraints?: readonly IdentityConstraint[]
	readonly textContent?: TextContent
}

/**
 * Complete definition — maps element names to their definitions.
 * Each dialecte should define its own specific type extending this.
 */
export type AnyDefinition = Record<string, ElementDefinition>
